### ISSUE TITLE
Clicks are getting ahead of themselves

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-test#22]
Some clicks are being triggered before the page is fully loaded, thus leaving the test stuck on the previous page.

**Comment by seav** [comment]
The test suite now has several functions that can be used to wait for elements to be visible, clickable, or gone depending on the situation: https://github.com/Cadasta/cadasta-test/blob/06d0911dd73955a6951469bd451914d32bf3f8e5/cadasta/test/webdriver.py#L49-L67
