### ISSUE TITLE
Upgrade to python3?

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-test#23]
This is more of a question: Since the Cadasta Platform is set-up for python3, my dev environment has python3 set as the default. I ran into several conflicts because these tests were looking for files in the python2 directory that existed in the python3 directory. Maybe it would make sense to have a python3 branch so that we have the option of both?

**Comment by shailysangwan** [comment]
As of now, there are two incompatibilities: ``index`` has been used to convert `int` to `str`, that can easily be changed to `str(index)`.
Second are the print calls, we can use `six.print_()`.
Should we make a separate branch or use [six](https://pypi.python.org/pypi/six)?

**Comment by shailysangwan** [comment]
As of now, there are two incompatibilities:
> Backticks has been used to convert `int` to `str`, that can easily be changed to `str()`.
> Second are the print calls, we can use `six.print_()` to fix them.

Should we make a separate branch or use [six](https://pypi.python.org/pypi/six)?

**Comment by shailysangwan** [comment]
As of now, there are two incompatibilities:
- Backticks has been used to convert `int` to `str`, that can easily be changed to `str()`.
- The print calls, we can use `six.print_()` to fix them.

Should we make a separate branch or use [six](https://pypi.python.org/pypi/six)?

**Comment by seav** [comment]
Resolved with #32.
